server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: DB_Ride_Hailing_SYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ridehailing?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # redis for windows
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON ignore not null
mybatis-plus:
  type-aliases-package: com.db_ride_hailing_sys.entity # 别名扫描包
logging:
  level:
    com.db_ride_hailing_sys: debug
  pattern:
    dateformat: mm:ss.SSS